import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Header from "@/src/components/sections/header";
import PageLayout from "@/src/components/GlobalLayout";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr-NE">
      <body
        className={`${lexend.className} antialiased min-h-screen bg-white`}
      >
        <PageLayout>        
          <Header/>
        {children}
        </PageLayout>

      </body>
    </html>
  );
}
